### ISSUE TITLE
Dependency on ROS Indigo

### ISSUE THREAD

**Issue by ankushdesai** [SRI-CSL/radler#3]
I have a Ubuntu 16.04 machine and am facing issues installing ROS Indigo.
Will Radler work with other versions of ROS?

**Comment by mkimsri** [comment]
Ankush, could you try Ubuntu 14.04 with Indigo?

**Comment by asundaresan** [comment]
I think 16.04 with kinetic ought to work too.

**Comment by lgerardSRI** [comment]
Yes, there is no known issue with Kinetic.
--
Léonard.

**Comment by mkimsri** [comment]
Ubuntu 16.04 with ROS Kinetic is working ok. Tested on Nvidia TX2.
